import Head from "next/head";
import Image from "next/image";
import {
    Button,
    Drawer,
    ListItem,
    ListItemIcon,
    ListItemText,
    List,
    Box,
} from "@mui/material";
import LoadingButton from "@mui/lab/LoadingButton";
import { InboxRounded } from "@mui/icons-material";
import Sidebar from "../components/Sidebar";
import Layout from "../components/Layout";
import { useState } from "react";
export default function Home() {
    const [loading, setLoading] = useState(false);
    return (
        <Box>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <LoadingButton
                    variant="contained"
                    loading={loading}
                    onClick={() => setLoading(!loading)}
                >
                    اهلا
                </LoadingButton>
                <Button onClick={() => setLoading(!loading)}>Toggle</Button>
            </Layout>
        </Box>
    );
}
